apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: vend-route
  namespace: {{ .Values.namespace_name }}
spec:
  port:
    targetPort: 3000
  to:
    kind: Service
    name: {{ .Values.service_name }}